# Generated by Django 5.0.2 on 2025-03-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="first_name",
            field=models.CharField(blank=True, max_length=30, verbose_name="Prénom"),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="last_name",
            field=models.CharField(blank=True, max_length=30, verbose_name="Nom"),
        ),
    ]
