# Generated by Django 5.0.2 on 2025-03-19 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_utilisateur_first_name_utilisateur_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name="URL de l'image de profil"),
        ),
    ]
