# Generated by Django 5.0.2 on 2025-03-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_utilisateur_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='type_utilisateur',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('MEMBRE_CSE', 'Membre CSE'), ('EMPLOYE', 'Employé'), ('RESPONSABLE', 'Responsable')], default='EMPLOYE', max_length=20, verbose_name="Type d'utilisateur"),
        ),
    ]
