# Generated by Django 5.0.2 on 2025-05-28 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_utilisateur_type_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='peut_creer_reunion',
            field=models.BooleanField(default=False, verbose_name='Peut créer des réunions'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='peut_modifier_fichier',
            field=models.BooleanField(default=False, verbose_name='Peut modifier/ajouter les fichiers'),
        ),
    ]
