# Generated by Django 5.0.2 on 2025-06-02 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_utilisateur_peut_creer_reunion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='peut_utiliser_ia',
            field=models.BooleanField(default=False, verbose_name="Peut utiliser l'IA"),
        ),
    ]
