# Generated by Django 5.0.2 on 2025-09-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='is_last_message_read',
            field=models.BooleanField(default=False, verbose_name='Dernier message lu'),
        ),
    ]
